### ISSUE TITLE
猜猜我是谁有错字

### ISSUE THREAD

**Issue by anzup** [yucendulang/DragaliaLostQQBot#1]
耶梦加得的试炼血亏项目，很多角色名字和游戏中的不同，因为一字只差不能继续游戏  白给10w水_(:з」∠)_

**Comment by yucendulang** [comment]
麻烦告诉我哪个错了我这边慢慢改..之前我随手写的...当时甚至没觉得这个title有用

**Comment by anzup** [comment]
目前遇到有休贝尔、拉托妮、安妮利艾，大概试了十几次里面有3、4个错字


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yucendulang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 中午11:59
收件人:&nbsp;"yucendulang/DragaliaLostQQBot"<DragaliaLostQQBot@noreply.github.com&gt;;
抄送:&nbsp;"木原"<1315220447@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yucendulang/DragaliaLostQQBot] 猜猜我是谁有错字 (#1)





 
麻烦告诉我哪个错了我这边慢慢改..之前我随手写的...当时甚至没觉得这个title有用

**Comment by yucendulang** [comment]
> 目前遇到有休贝尔、拉托妮、安妮利艾，大概试了十几次里面有3、4个错字
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"yucendulang"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月2日(星期四) 中午11:59 收件人:&nbsp;"yucendulang/DragaliaLostQQBot"<DragaliaLostQQBot@noreply.github.com&gt;; 抄送:&nbsp;"木原"<1315220447@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [yucendulang/DragaliaLostQQBot] 猜猜我是谁有错字 (#1) 麻烦告诉我哪个错了我这边慢慢改..之前我随手写的...当时甚至没觉得这个title有用 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这几个都改了 感谢反馈
